def la_mia_funzione(parametro1: int, parametro2: str) -> str:
    """Questa funzione prende 2 parametri e 
    fa .......
    
    Ci sono queste considerazioni :
    1....
    2....
    3....
    """
    return 5

